package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "gxctabbarcontroller_library",
    srcs = glob(["**/*.swift"]),
    deps = [
        "@rxswift//:RxCocoa",
    ],
    module_name = "TabBarController_library"
)
